#!/bin/bash
#PBS -j oe
#PBS -m ae
#PBS -N metaquast
#PBS -l walltime=100:00:00
#PBS -l select=1:ncpus=16:mem=240gb
#PBS -M paul.obrien@my.jcu.edu.au

cd $PBS_O_WORKDIR
shopt -s expand_aliases
source /etc/profile.d/modules.sh
echo "Job identifier is $PBS_JOBID"
echo "Working directory is $PBS_O_WORKDIR"


##########################################


### CHECK ASSEMBLY STATISTICS WITH METAQUAST ###


### LOAD MODULES ###

module load anaconda3/2019.10 

# Following line is needed for conda activate to work
. ~/.bashrc 

conda activate quast


### RUN METAQUAST ###

metaquast /scratch/jc254091/Metagenomics/MetaSpades/*/scaffolds.fasta -o /scratch/jc254091/Metagenomics/Quast -t 16





