#!/bin/bash
#PBS -j oe
#PBS -m ae
#PBS -N maxbin2
#PBS -l walltime=100:00:00
#PBS -l select=1:ncpus=8:mem=16gb
#PBS -M paul.obrien@my.jcu.edu.au

cd $PBS_O_WORKDIR
shopt -s expand_aliases
source /etc/profile.d/modules.sh
echo "Job identifier is $PBS_JOBID"
echo "Working directory is $PBS_O_WORKDIR"


##########################################


### Bin contigs/scaffolds into putative genomes using maxbin2 ###


### LOAD MODULES ###

module load anaconda3/2019.10
module load R/3.5.2
. ~/.bashrc
conda activate maxbin2


### RUN MAXBIN2 ###


###############
### BY HOST ###
###############


# Bin contigs using coverage of mapping reads to scaffolds by host species

for FILE in $(ls ~/Metagenomics/Assembly_and_binning/MetaSpades/*_spades/scaffolds.fasta); do

# Set up variable 
  PREFIX=$(echo $FILE | cut -d "/" -f 7 | cut -d "_" -f 1)

# Check variables
  echo "file is $FILE"
  echo "prefix is $PREFIX"

# make output dir
  mkdir ~/Metagenomics/Assembly_and_binning/Maxbin/${PREFIX}_bins/

# bin contigs
  run_MaxBin.pl \
      -contig $FILE \
      -out ~/Metagenomics/Assembly_and_binning/Maxbin/${PREFIX}_bins/${PREFIX}_bin \
      -abund ~/Metagenomics/Assembly_and_binning/Coverage_files/By_host/${PREFIX}_depth.txt \
      -min_contig_length 2000 \
      -thread 8 \
      -plotmarker
done





